apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    - name: go-dots-server
      image: eurekaeru/go-dots:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;"]
      ports:
      - containerPort: 4646
        name: signalchannel
      - containerPort: 10443
        name: datachannel
      workingDir: "/dots/config"
      volumeMounts:
      - mountPath: "/dots"
        name: volume-config-dots
      - mountPath: "/usr/lib/mysql/plugin"
        name: volume-mysql-notification
    - name: mysql
      image: mysql:5.7.28
      args: [ "--default-authentication-plugin=mysql_native_password" ]
      env:
      - name: "MYSQL_DATABASE"
        value: "dots"
      - name: "MYSQL_ROOT_PASSWORD"
        value: "root"
      ports:
      - containerPort: 3306
      workingDir: "/dots/config"
      volumeMounts:
      - mountPath: "/dots"
        name: volume-config-dots
      - mountPath: "/usr/lib/mysql/plugin"
        name: volume-mysql-notification
    - name: gobgp
      image: osrg/gobgp:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      workingDir: "/dots/config"
      volumeMounts:
      - mountPath: "/dots"
        name: volume-config-dots
  volumes:
  - name: volume-config-dots
    hostPath:
      path: "/dots"
      type: Directory
  - name: volume-mysql-notification
    emptyDir: {}





---

apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: go-dots-client
      image: eurekaeru/go-dots:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      ports:
      - containerPort: 4646
      workingDir: "/dots/config"
      volumeMounts:
      - mountPath: "/dots"
        name: volume-config-dots
  volumes:
  - name: volume-config-dots
    hostPath:
      path: "/dots"